language: php

php:
  - 7.1
  - hhvm

before_script:
  - composer install --dev --no-interaction --prefer-dist
  - mkdir -p build/logs/

script:
  - php vendor/bin/kahlan --cc=true --coverage=4 --clover=build/logs/clover.xml

after_success:
  - php vendor/bin/coveralls.php -v
